# Generated by Django 3.1.7 on 2021-02-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modile',
            new_name='Module',
        ),
    ]
